# Generated by Django 4.2.5 on 2023-09-23 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_tiers_remove_customuser_img_uploaded_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tiers',
            old_name='name',
            new_name='tier_type',
        ),
    ]
