# Generated by Django 4.2.5 on 2023-09-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("image_drf_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="status",
            field=models.CharField(
                choices=[
                    ("basic", "Basic"),
                    ("premium", "Premium"),
                    ("enterprise", "Enterprise"),
                ],
                default="basic",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="img_uploaded",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
