# Generated by Django 4.2.5 on 2023-09-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_drf_app', '0003_alter_customuser_img_uploaded_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='thumbnail_200',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails_200/'),
        ),
        migrations.AddField(
            model_name='images',
            name='thumbnail_400',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails_400/'),
        ),
    ]
